### ISSUE TITLE
自定义事件，如果需要像重点事件一样，显示所有内容，正则匹配处应该填写什么内容呢？

### ISSUE THREAD

**Issue by Peehsa** [xbaogua/BaoGuaWindowsEvent#1]

**Comment by xbaogua** [comment]
自定义事件如果想匹配全部内容可以使用正则   ^[\s\S]*$  ，但是需要注意，重点事件展示结果是经过解析的，使用正则匹配结果如果有换行，在界面显示也会出现换行（可能会导致结果展示有些乱）
