### ISSUE TITLE
v1.0.0.3版本的一些小问题

### ISSUE THREAD

**Issue by K4ack2013** [xbaogua/BaoGuaWindowsEvent#2]
首先感谢作者开发出这个小工具，很好用。
我想提2个小意见。
1、默认选择重点事件的话，他是直接匹配日志所有的字段我可以很清楚的看到这些信息。我自定义事件的话也想像重点事件功能那样自动匹配关键字段方便人员看（不需要人工单独写正则），如果需要人工写正则的话我需要怎么写，有没有好一点的例子。
2、重点事件的话，可不可以多加一些内置规则（从一些开源的软件里直接提取ID号，和对应的注解）
推荐项目：
https://github.com/Yamato-Security/hayabusa/
https://github.com/ahmedkhlief/APT-Hunter

**Comment by daymissed** [comment]
认为这两个意见很实用，希望大佬能改进。

**Comment by xbaogua** [comment]
感谢二位的建议，目前已经着手在改进啦。
1、原有自定义事件通过正则匹配确实不方便，正在已经调整为自定义模板的方式，比如：Security的5156事件
![image](https://github.com/xbaogua/BaoGuaWindowsEvent/assets/103565342/2264ae1e-f819-4445-ae86-e9282f88a7fb)
2、重点事件目前在逐步补充中

**Comment by gongdidi** [comment]
你好，这个报错是什么问题啊
![1715908973974](https://github.com/xbaogua/BaoGuaWindowsEvent/assets/117560708/4a3abb0d-c8e9-445c-8765-5d195568d931)

**Comment by xbaogua** [comment]
> 你好，这个报错是什么问题啊 ![1715908973974](https://private-user-images.githubusercontent.com/117560708/331428424-4a3abb0d-c8e9-445c-8765-5d195568d931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTEwNDMsIm5iZiI6MTcxNTkxMDc0MywicGF0aCI6Ii8xMTc1NjA3MDgvMzMxNDI4NDI0LTRhM2FiYjBkLWM4ZTktNDQ1Yy04NzY1LTVkMTk1NTY4ZDkzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTg2YTNlNjk0N2NkNGYwNzBlNzI5N2I2Mjg4MDRjOTNiZjZlYThjNTYyN2UwNDM2ZGFkZTQ2NDdiMGNkYThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4IFA3HBAFaps1FEjn4lbCHTLcMqe4ee5MPL-q80xUfU)

把日志拷贝出来，读取拷贝出来的日志就可以了，现在日志被系统占用，需要管理员权限才能读取。

**Comment by muxinmufei** [comment]
很棒的工具！期待作者更新匹配方式 正则的确不是很方便

**Comment by xbaogua** [comment]
已更新到v1.0.0.8版本，欢迎大家使用新版本，本issue关闭。
