### ISSUE TITLE
能否同时选择内置规则和自定义规则进行解析？

### ISSUE THREAD

**Issue by KingLann** [xbaogua/BaoGuaWindowsEvent#6]
在使用时发现，要么只能使用内置规则，要么只能使用自定义规则，能否考虑增加一个功能，能够同时选择内置规则和自定义规则进行解析？

**Comment by xbaogua** [comment]
好建议！目前在选项中增加一项“全部规则”，选中该项就会同时使用内置规则和自定义规则，而且自定义的规则优先级会高于内置规则，如果自定义规则和内置规则同时存在的话，会优先展示自定义规则，这样，如果有内置规则不够合理或者觉得显示的内容太多，就可以用自定义规则覆盖

**Comment by xbaogua** [comment]
已更新
